# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20171126_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_purchases', to='pet.Pet'),
        ),
    ]
