# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_auto_20171127_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='petCode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
