# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_auto_20171127_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_images',
            field=models.ManyToManyField(blank=True, related_name='users_like', to='pet.PetGallery'),
        ),
    ]
